### ISSUE TITLE
installation documentation muon-galaxy-tools branch

### ISSUE THREAD

**Issue by agbeltran** [muon-spectroscopy-computational-project/muon-galaxy#2]
The installation documentation at:
https://github.com/muon-spectroscopy-computational-project/muon-galaxy/blob/eli/combine-changes/muon_galaxy_installation.md

refers to 

```git clone --branch eli/add-pm-muairss https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools```

but the branch ```eli/add-pm-muairss```  in ```muon-galaxy-tools``` does not exist.

Probably refers to the branch ```eli/add-pm-muairss-write```:

https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/tree/eli/add-pm-muairss-write

**Comment by elichad** [comment]
Documentation moved to https://github.com/muon-spectroscopy-computational-project/Developer-notes/blob/main/muon-galaxy-installation/basic_installation.md, now references `crystvis_22.05` which is the most recent branch as of now.
