### ISSUE TITLE
Request .param file when calculator : castep

### ISSUE THREAD

**Issue by leandro-liborio** [muon-spectroscopy-computational-project/muon-galaxy#3]
To find the muon stopping site of muonium, we need to run pm-muairss with the 'calculator' parameter in the ".yaml" files as being 'dftb+' (the default) or 'castep'.  If we use 'castep', we need to add in Galaxy the possibility of loading  a .param file together with the corresponding ".cell" and ".yaml" file.  Otherwise, we get an error message when generating the muon_airss_out folder.

The way the method works in this case is by running castep relaxations for every muonated structure that was created. For that, we need the .cell and the .param file.

**Comment by Jo-stfc** [comment]
Is this during the muairss write step?
